// Content Credentials, read straight off the bytes the author picked.
//
// Every generator that labels its output writes the same IPTC field — digitalSourceType —
// either into an XMP packet (JPEG APP1, PNG iTXt, WebP "XMP " chunk) or into a C2PA manifest
// (JPEG APP11 JUMBF, PNG caBX, WebP and MP4 boxes). The containers differ; the marker does not.
// XMP is UTF-8 and CBOR stores its text strings literally, so a single substring scan finds it
// in all of them — no container parser, no WASM verifier, not a single decoded pixel.
//
// What this is NOT: proof. It reports what the file says about itself. A screenshot, a re-encode,
// or a generator that writes nothing all come back clean, and nothing here can tell the
// difference between "not AI" and "not labeled". It is the same bargain every platform makes.

// Metadata rides at the head of a JPEG, PNG and MP4, and at the tail of a WebP (RIFF parks
// EXIF/XMP after the image data) — and MP4 puts its C2PA box after mdat when written by a
// remuxer. Two small reads cover every case; a 4K JPEG's manifest is a few KB.
const HEAD_BYTES = 512 * 1024
const TAIL_BYTES = 256 * 1024

// The IPTC vocabulary, matched on the trailing term so the scan is agnostic to whether the
// file spells out the full http://cv.iptc.org/newscodes/digitalsourcetype/ URI or the bare value.
//
// trainedAlgorithmicMedia — generated by a model (DALL·E, Imagen, Firefly, Sora)
// compositeSynthetic     — real media with model-generated elements composited in (generative fill)
//
// algorithmicallyEnhanced is deliberately absent: that covers denoise, upscale and every phone
// camera's night mode, and badging those would put the label on half the images on the internet.
const IPTC_MARKERS = ['trainedAlgorithmicMedia', 'compositeSynthetic']

// Tools that ship no IPTC field but do sign their work in a way that is unambiguous.
// Deliberately narrow — anything that could appear in an ordinary file's metadata is left out,
// because a false badge on a human's photo is worse than a missing one on a model's output.
const GENERATOR_MARKERS = [
  'Midjourney', // Description/Software on a Midjourney export
  'stable-diffusion', // invoke/comfy pipelines write the model id
  'Stable Diffusion',
  'Sampler: Euler', // Automatic1111 dumps its whole run into a PNG `parameters` chunk
]

const decoder = typeof TextDecoder === 'undefined' ? null : new TextDecoder('latin1')

// Latin-1, not UTF-8: this is a byte-for-byte view, so a multi-byte sequence or a stray 0xFF in
// the compressed data can never abort the decode or swallow the bytes next to it. Every marker
// is ASCII, so an ASCII-transparent decoding is all the scan needs.
const readSlice = async (file, start, end) => {
  try {
    const buffer = await file.slice(start, end).arrayBuffer()
    return decoder.decode(new Uint8Array(buffer))
  } catch {
    return ''
  }
}

const findMarker = (text, markers) => markers.find((marker) => text.includes(marker))

/**
 * Inspect a file's own metadata for a declaration that a model made it.
 *
 * @param {File|Blob} file the ORIGINAL file, before any re-encode — see the note in NewPost's
 *   upload path: the video optimizer produces a clean H.264 rendition with every metadata block
 *   dropped, so a scan run after it would report nothing on a file that had a manifest.
 * @returns {Promise<{ aiGenerated: boolean, marker?: string }>}
 */
export async function detectAiProvenance(file) {
  if (!file || !decoder || typeof file.slice !== 'function') return { aiGenerated: false }

  const head = await readSlice(file, 0, Math.min(HEAD_BYTES, file.size))
  let marker = findMarker(head, IPTC_MARKERS) || findMarker(head, GENERATOR_MARKERS)

  // Only pay for the second read when the first found nothing and the file is big enough to
  // have a tail the head did not already cover
  if (!marker && file.size > HEAD_BYTES) {
    const tail = await readSlice(file, Math.max(HEAD_BYTES, file.size - TAIL_BYTES), file.size)
    marker = findMarker(tail, IPTC_MARKERS) || findMarker(tail, GENERATOR_MARKERS)
  }

  return marker ? { aiGenerated: true, marker } : { aiGenerated: false }
}
