allowBuilds:
  '@google/genai': true
  '@parcel/watcher': false
  '@reown/appkit': false
  bufferutil: false
  es5-ext: false
  protobufjs: false
  secp256k1: false
  sharp: false
  unrs-resolver: false
  utf-8-validate: false
