allowBuilds:
  '@google/genai': set this to true or false
  '@parcel/watcher': set this to true or false
  '@reown/appkit': set this to true or false
  bufferutil: set this to true or false
  es5-ext: set this to true or false
  protobufjs: set this to true or false
  secp256k1: set this to true or false
  sharp: set this to true or false
  unrs-resolver: set this to true or false
  utf-8-validate: set this to true or false
