allowBuilds:
  '@google/genai': true
  '@parcel/watcher': true
  '@reown/appkit': true
  bufferutil: true
  es5-ext: true
  protobufjs: true
  secp256k1: true
  sharp: true
  unrs-resolver: true
  utf-8-validate: true
