-- The country list the profile origin picker offers and the profile save validates against.
--
-- Only needed where `countries` does not already exist — a deployment that has it (it predates
-- this feature, having been added for a merchant flow that never shipped) needs nothing from this
-- file. Both halves are guarded, so running it against a populated table is a no-op.
--
-- 249 rows of ISO 3166-1: `iso_code` is the identity that lands on `users.origin_code`; `id` is
-- carried only to keep copies of this table aligned, and nothing in the app ever reads it.
--
-- Apply 2026-08-20-profile-origin.sql after this one — it puts the unique key on `iso_code` that
-- the per-save lookup needs.

CREATE TABLE IF NOT EXISTS `countries` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `name` varchar(100) NOT NULL,
  `iso_code` varchar(5) NOT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

INSERT IGNORE INTO `countries` (`id`, `name`, `iso_code`) VALUES (1,'Afghanistan','AF');
INSERT IGNORE INTO `countries` (`id`, `name`, `iso_code`) VALUES (2,'Åland Islands','AX');
INSERT IGNORE INTO `countries` (`id`, `name`, `iso_code`) VALUES (3,'Albania','AL');
INSERT IGNORE INTO `countries` (`id`, `name`, `iso_code`) VALUES (4,'Algeria','DZ');
INSERT IGNORE INTO `countries` (`id`, `name`, `iso_code`) VALUES (5,'American Samoa','AS');
INSERT IGNORE INTO `countries` (`id`, `name`, `iso_code`) VALUES (6,'Andorra','AD');
INSERT IGNORE INTO `countries` (`id`, `name`, `iso_code`) VALUES (7,'Angola','AO');
INSERT IGNORE INTO `countries` (`id`, `name`, `iso_code`) VALUES (8,'Anguilla','AI');
INSERT IGNORE INTO `countries` (`id`, `name`, `iso_code`) VALUES (9,'Antarctica','AQ');
INSERT IGNORE INTO `countries` (`id`, `name`, `iso_code`) VALUES (10,'Antigua and Barbuda','AG');
INSERT IGNORE INTO `countries` (`id`, `name`, `iso_code`) VALUES (11,'Argentina','AR');
INSERT IGNORE INTO `countries` (`id`, `name`, `iso_code`) VALUES (12,'Armenia','AM');
INSERT IGNORE INTO `countries` (`id`, `name`, `iso_code`) VALUES (13,'Aruba','AW');
INSERT IGNORE INTO `countries` (`id`, `name`, `iso_code`) VALUES (14,'Australia','AU');
INSERT IGNORE INTO `countries` (`id`, `name`, `iso_code`) VALUES (15,'Austria','AT');
INSERT IGNORE INTO `countries` (`id`, `name`, `iso_code`) VALUES (16,'Azerbaijan','AZ');
INSERT IGNORE INTO `countries` (`id`, `name`, `iso_code`) VALUES (17,'Bahamas','BS');
INSERT IGNORE INTO `countries` (`id`, `name`, `iso_code`) VALUES (18,'Bahrain','BH');
INSERT IGNORE INTO `countries` (`id`, `name`, `iso_code`) VALUES (19,'Bangladesh','BD');
INSERT IGNORE INTO `countries` (`id`, `name`, `iso_code`) VALUES (20,'Barbados','BB');
INSERT IGNORE INTO `countries` (`id`, `name`, `iso_code`) VALUES (21,'Belarus','BY');
INSERT IGNORE INTO `countries` (`id`, `name`, `iso_code`) VALUES (22,'Belgium','BE');
INSERT IGNORE INTO `countries` (`id`, `name`, `iso_code`) VALUES (23,'Belize','BZ');
INSERT IGNORE INTO `countries` (`id`, `name`, `iso_code`) VALUES (24,'Benin','BJ');
INSERT IGNORE INTO `countries` (`id`, `name`, `iso_code`) VALUES (25,'Bermuda','BM');
INSERT IGNORE INTO `countries` (`id`, `name`, `iso_code`) VALUES (26,'Bhutan','BT');
INSERT IGNORE INTO `countries` (`id`, `name`, `iso_code`) VALUES (27,'Bolivia','BO');
INSERT IGNORE INTO `countries` (`id`, `name`, `iso_code`) VALUES (28,'Bonaire, Sint Eustatius and Saba','BQ');
INSERT IGNORE INTO `countries` (`id`, `name`, `iso_code`) VALUES (29,'Bosnia and Herzegovina','BA');
INSERT IGNORE INTO `countries` (`id`, `name`, `iso_code`) VALUES (30,'Botswana','BW');
INSERT IGNORE INTO `countries` (`id`, `name`, `iso_code`) VALUES (31,'Bouvet Island','BV');
INSERT IGNORE INTO `countries` (`id`, `name`, `iso_code`) VALUES (32,'Brazil','BR');
INSERT IGNORE INTO `countries` (`id`, `name`, `iso_code`) VALUES (33,'British Indian Ocean Territory','IO');
INSERT IGNORE INTO `countries` (`id`, `name`, `iso_code`) VALUES (34,'Brunei Darussalam','BN');
INSERT IGNORE INTO `countries` (`id`, `name`, `iso_code`) VALUES (35,'Bulgaria','BG');
INSERT IGNORE INTO `countries` (`id`, `name`, `iso_code`) VALUES (36,'Burkina Faso','BF');
INSERT IGNORE INTO `countries` (`id`, `name`, `iso_code`) VALUES (37,'Burundi','BI');
INSERT IGNORE INTO `countries` (`id`, `name`, `iso_code`) VALUES (38,'Cabo Verde','CV');
INSERT IGNORE INTO `countries` (`id`, `name`, `iso_code`) VALUES (39,'Cambodia','KH');
INSERT IGNORE INTO `countries` (`id`, `name`, `iso_code`) VALUES (40,'Cameroon','CM');
INSERT IGNORE INTO `countries` (`id`, `name`, `iso_code`) VALUES (41,'Canada','CA');
INSERT IGNORE INTO `countries` (`id`, `name`, `iso_code`) VALUES (42,'Cayman Islands','KY');
INSERT IGNORE INTO `countries` (`id`, `name`, `iso_code`) VALUES (43,'Central African Republic','CF');
INSERT IGNORE INTO `countries` (`id`, `name`, `iso_code`) VALUES (44,'Chad','TD');
INSERT IGNORE INTO `countries` (`id`, `name`, `iso_code`) VALUES (45,'Chile','CL');
INSERT IGNORE INTO `countries` (`id`, `name`, `iso_code`) VALUES (46,'China','CN');
INSERT IGNORE INTO `countries` (`id`, `name`, `iso_code`) VALUES (47,'Christmas Island','CX');
INSERT IGNORE INTO `countries` (`id`, `name`, `iso_code`) VALUES (48,'Cocos (Keeling) Islands','CC');
INSERT IGNORE INTO `countries` (`id`, `name`, `iso_code`) VALUES (49,'Colombia','CO');
INSERT IGNORE INTO `countries` (`id`, `name`, `iso_code`) VALUES (50,'Comoros','KM');
INSERT IGNORE INTO `countries` (`id`, `name`, `iso_code`) VALUES (51,'Congo','CG');
INSERT IGNORE INTO `countries` (`id`, `name`, `iso_code`) VALUES (52,'Congo, Democratic Republic of the','CD');
INSERT IGNORE INTO `countries` (`id`, `name`, `iso_code`) VALUES (53,'Cook Islands','CK');
INSERT IGNORE INTO `countries` (`id`, `name`, `iso_code`) VALUES (54,'Costa Rica','CR');
INSERT IGNORE INTO `countries` (`id`, `name`, `iso_code`) VALUES (55,'Côte d\'Ivoire','CI');
INSERT IGNORE INTO `countries` (`id`, `name`, `iso_code`) VALUES (56,'Croatia','HR');
INSERT IGNORE INTO `countries` (`id`, `name`, `iso_code`) VALUES (57,'Cuba','CU');
INSERT IGNORE INTO `countries` (`id`, `name`, `iso_code`) VALUES (58,'Curaçao','CW');
INSERT IGNORE INTO `countries` (`id`, `name`, `iso_code`) VALUES (59,'Cyprus','CY');
INSERT IGNORE INTO `countries` (`id`, `name`, `iso_code`) VALUES (60,'Czechia','CZ');
INSERT IGNORE INTO `countries` (`id`, `name`, `iso_code`) VALUES (61,'Denmark','DK');
INSERT IGNORE INTO `countries` (`id`, `name`, `iso_code`) VALUES (62,'Djibouti','DJ');
INSERT IGNORE INTO `countries` (`id`, `name`, `iso_code`) VALUES (63,'Dominica','DM');
INSERT IGNORE INTO `countries` (`id`, `name`, `iso_code`) VALUES (64,'Dominican Republic','DO');
INSERT IGNORE INTO `countries` (`id`, `name`, `iso_code`) VALUES (65,'Ecuador','EC');
INSERT IGNORE INTO `countries` (`id`, `name`, `iso_code`) VALUES (66,'Egypt','EG');
INSERT IGNORE INTO `countries` (`id`, `name`, `iso_code`) VALUES (67,'El Salvador','SV');
INSERT IGNORE INTO `countries` (`id`, `name`, `iso_code`) VALUES (68,'Equatorial Guinea','GQ');
INSERT IGNORE INTO `countries` (`id`, `name`, `iso_code`) VALUES (69,'Eritrea','ER');
INSERT IGNORE INTO `countries` (`id`, `name`, `iso_code`) VALUES (70,'Estonia','EE');
INSERT IGNORE INTO `countries` (`id`, `name`, `iso_code`) VALUES (71,'Eswatini','SZ');
INSERT IGNORE INTO `countries` (`id`, `name`, `iso_code`) VALUES (72,'Ethiopia','ET');
INSERT IGNORE INTO `countries` (`id`, `name`, `iso_code`) VALUES (73,'Falkland Islands (Malvinas)','FK');
INSERT IGNORE INTO `countries` (`id`, `name`, `iso_code`) VALUES (74,'Faroe Islands','FO');
INSERT IGNORE INTO `countries` (`id`, `name`, `iso_code`) VALUES (75,'Fiji','FJ');
INSERT IGNORE INTO `countries` (`id`, `name`, `iso_code`) VALUES (76,'Finland','FI');
INSERT IGNORE INTO `countries` (`id`, `name`, `iso_code`) VALUES (77,'France','FR');
INSERT IGNORE INTO `countries` (`id`, `name`, `iso_code`) VALUES (78,'French Guiana','GF');
INSERT IGNORE INTO `countries` (`id`, `name`, `iso_code`) VALUES (79,'French Polynesia','PF');
INSERT IGNORE INTO `countries` (`id`, `name`, `iso_code`) VALUES (80,'French Southern Territories','TF');
INSERT IGNORE INTO `countries` (`id`, `name`, `iso_code`) VALUES (81,'Gabon','GA');
INSERT IGNORE INTO `countries` (`id`, `name`, `iso_code`) VALUES (82,'Gambia','GM');
INSERT IGNORE INTO `countries` (`id`, `name`, `iso_code`) VALUES (83,'Georgia','GE');
INSERT IGNORE INTO `countries` (`id`, `name`, `iso_code`) VALUES (84,'Germany','DE');
INSERT IGNORE INTO `countries` (`id`, `name`, `iso_code`) VALUES (85,'Ghana','GH');
INSERT IGNORE INTO `countries` (`id`, `name`, `iso_code`) VALUES (86,'Gibraltar','GI');
INSERT IGNORE INTO `countries` (`id`, `name`, `iso_code`) VALUES (87,'Greece','GR');
INSERT IGNORE INTO `countries` (`id`, `name`, `iso_code`) VALUES (88,'Greenland','GL');
INSERT IGNORE INTO `countries` (`id`, `name`, `iso_code`) VALUES (89,'Grenada','GD');
INSERT IGNORE INTO `countries` (`id`, `name`, `iso_code`) VALUES (90,'Guadeloupe','GP');
INSERT IGNORE INTO `countries` (`id`, `name`, `iso_code`) VALUES (91,'Guam','GU');
INSERT IGNORE INTO `countries` (`id`, `name`, `iso_code`) VALUES (92,'Guatemala','GT');
INSERT IGNORE INTO `countries` (`id`, `name`, `iso_code`) VALUES (93,'Guernsey','GG');
INSERT IGNORE INTO `countries` (`id`, `name`, `iso_code`) VALUES (94,'Guinea','GN');
INSERT IGNORE INTO `countries` (`id`, `name`, `iso_code`) VALUES (95,'Guinea-Bissau','GW');
INSERT IGNORE INTO `countries` (`id`, `name`, `iso_code`) VALUES (96,'Guyana','GY');
INSERT IGNORE INTO `countries` (`id`, `name`, `iso_code`) VALUES (97,'Haiti','HT');
INSERT IGNORE INTO `countries` (`id`, `name`, `iso_code`) VALUES (98,'Heard Island and McDonald Islands','HM');
INSERT IGNORE INTO `countries` (`id`, `name`, `iso_code`) VALUES (99,'Holy See','VA');
INSERT IGNORE INTO `countries` (`id`, `name`, `iso_code`) VALUES (100,'Honduras','HN');
INSERT IGNORE INTO `countries` (`id`, `name`, `iso_code`) VALUES (101,'Hong Kong','HK');
INSERT IGNORE INTO `countries` (`id`, `name`, `iso_code`) VALUES (102,'Hungary','HU');
INSERT IGNORE INTO `countries` (`id`, `name`, `iso_code`) VALUES (103,'Iceland','IS');
INSERT IGNORE INTO `countries` (`id`, `name`, `iso_code`) VALUES (104,'India','IN');
INSERT IGNORE INTO `countries` (`id`, `name`, `iso_code`) VALUES (105,'Indonesia','ID');
INSERT IGNORE INTO `countries` (`id`, `name`, `iso_code`) VALUES (106,'Iran','IR');
INSERT IGNORE INTO `countries` (`id`, `name`, `iso_code`) VALUES (107,'Iraq','IQ');
INSERT IGNORE INTO `countries` (`id`, `name`, `iso_code`) VALUES (108,'Ireland','IE');
INSERT IGNORE INTO `countries` (`id`, `name`, `iso_code`) VALUES (109,'Isle of Man','IM');
INSERT IGNORE INTO `countries` (`id`, `name`, `iso_code`) VALUES (110,'Israel','IL');
INSERT IGNORE INTO `countries` (`id`, `name`, `iso_code`) VALUES (111,'Italy','IT');
INSERT IGNORE INTO `countries` (`id`, `name`, `iso_code`) VALUES (112,'Jamaica','JM');
INSERT IGNORE INTO `countries` (`id`, `name`, `iso_code`) VALUES (113,'Japan','JP');
INSERT IGNORE INTO `countries` (`id`, `name`, `iso_code`) VALUES (114,'Jersey','JE');
INSERT IGNORE INTO `countries` (`id`, `name`, `iso_code`) VALUES (115,'Jordan','JO');
INSERT IGNORE INTO `countries` (`id`, `name`, `iso_code`) VALUES (116,'Kazakhstan','KZ');
INSERT IGNORE INTO `countries` (`id`, `name`, `iso_code`) VALUES (117,'Kenya','KE');
INSERT IGNORE INTO `countries` (`id`, `name`, `iso_code`) VALUES (118,'Kiribati','KI');
INSERT IGNORE INTO `countries` (`id`, `name`, `iso_code`) VALUES (119,'Korea, Democratic People\'s Republic of','KP');
INSERT IGNORE INTO `countries` (`id`, `name`, `iso_code`) VALUES (120,'Korea, Republic of','KR');
INSERT IGNORE INTO `countries` (`id`, `name`, `iso_code`) VALUES (121,'Kuwait','KW');
INSERT IGNORE INTO `countries` (`id`, `name`, `iso_code`) VALUES (122,'Kyrgyzstan','KG');
INSERT IGNORE INTO `countries` (`id`, `name`, `iso_code`) VALUES (123,'Lao People\'s Democratic Republic','LA');
INSERT IGNORE INTO `countries` (`id`, `name`, `iso_code`) VALUES (124,'Latvia','LV');
INSERT IGNORE INTO `countries` (`id`, `name`, `iso_code`) VALUES (125,'Lebanon','LB');
INSERT IGNORE INTO `countries` (`id`, `name`, `iso_code`) VALUES (126,'Lesotho','LS');
INSERT IGNORE INTO `countries` (`id`, `name`, `iso_code`) VALUES (127,'Liberia','LR');
INSERT IGNORE INTO `countries` (`id`, `name`, `iso_code`) VALUES (128,'Libya','LY');
INSERT IGNORE INTO `countries` (`id`, `name`, `iso_code`) VALUES (129,'Liechtenstein','LI');
INSERT IGNORE INTO `countries` (`id`, `name`, `iso_code`) VALUES (130,'Lithuania','LT');
INSERT IGNORE INTO `countries` (`id`, `name`, `iso_code`) VALUES (131,'Luxembourg','LU');
INSERT IGNORE INTO `countries` (`id`, `name`, `iso_code`) VALUES (132,'Macao','MO');
INSERT IGNORE INTO `countries` (`id`, `name`, `iso_code`) VALUES (133,'Madagascar','MG');
INSERT IGNORE INTO `countries` (`id`, `name`, `iso_code`) VALUES (134,'Malawi','MW');
INSERT IGNORE INTO `countries` (`id`, `name`, `iso_code`) VALUES (135,'Malaysia','MY');
INSERT IGNORE INTO `countries` (`id`, `name`, `iso_code`) VALUES (136,'Maldives','MV');
INSERT IGNORE INTO `countries` (`id`, `name`, `iso_code`) VALUES (137,'Mali','ML');
INSERT IGNORE INTO `countries` (`id`, `name`, `iso_code`) VALUES (138,'Malta','MT');
INSERT IGNORE INTO `countries` (`id`, `name`, `iso_code`) VALUES (139,'Marshall Islands','MH');
INSERT IGNORE INTO `countries` (`id`, `name`, `iso_code`) VALUES (140,'Martinique','MQ');
INSERT IGNORE INTO `countries` (`id`, `name`, `iso_code`) VALUES (141,'Mauritania','MR');
INSERT IGNORE INTO `countries` (`id`, `name`, `iso_code`) VALUES (142,'Mauritius','MU');
INSERT IGNORE INTO `countries` (`id`, `name`, `iso_code`) VALUES (143,'Mayotte','YT');
INSERT IGNORE INTO `countries` (`id`, `name`, `iso_code`) VALUES (144,'Mexico','MX');
INSERT IGNORE INTO `countries` (`id`, `name`, `iso_code`) VALUES (145,'Micronesia','FM');
INSERT IGNORE INTO `countries` (`id`, `name`, `iso_code`) VALUES (146,'Moldova','MD');
INSERT IGNORE INTO `countries` (`id`, `name`, `iso_code`) VALUES (147,'Monaco','MC');
INSERT IGNORE INTO `countries` (`id`, `name`, `iso_code`) VALUES (148,'Mongolia','MN');
INSERT IGNORE INTO `countries` (`id`, `name`, `iso_code`) VALUES (149,'Montenegro','ME');
INSERT IGNORE INTO `countries` (`id`, `name`, `iso_code`) VALUES (150,'Montserrat','MS');
INSERT IGNORE INTO `countries` (`id`, `name`, `iso_code`) VALUES (151,'Morocco','MA');
INSERT IGNORE INTO `countries` (`id`, `name`, `iso_code`) VALUES (152,'Mozambique','MZ');
INSERT IGNORE INTO `countries` (`id`, `name`, `iso_code`) VALUES (153,'Myanmar','MM');
INSERT IGNORE INTO `countries` (`id`, `name`, `iso_code`) VALUES (154,'Namibia','NA');
INSERT IGNORE INTO `countries` (`id`, `name`, `iso_code`) VALUES (155,'Nauru','NR');
INSERT IGNORE INTO `countries` (`id`, `name`, `iso_code`) VALUES (156,'Nepal','NP');
INSERT IGNORE INTO `countries` (`id`, `name`, `iso_code`) VALUES (157,'Netherlands','NL');
INSERT IGNORE INTO `countries` (`id`, `name`, `iso_code`) VALUES (158,'New Caledonia','NC');
INSERT IGNORE INTO `countries` (`id`, `name`, `iso_code`) VALUES (159,'New Zealand','NZ');
INSERT IGNORE INTO `countries` (`id`, `name`, `iso_code`) VALUES (160,'Nicaragua','NI');
INSERT IGNORE INTO `countries` (`id`, `name`, `iso_code`) VALUES (161,'Niger','NE');
INSERT IGNORE INTO `countries` (`id`, `name`, `iso_code`) VALUES (162,'Nigeria','NG');
INSERT IGNORE INTO `countries` (`id`, `name`, `iso_code`) VALUES (163,'Niue','NU');
INSERT IGNORE INTO `countries` (`id`, `name`, `iso_code`) VALUES (164,'Norfolk Island','NF');
INSERT IGNORE INTO `countries` (`id`, `name`, `iso_code`) VALUES (165,'North Macedonia','MK');
INSERT IGNORE INTO `countries` (`id`, `name`, `iso_code`) VALUES (166,'Northern Mariana Islands','MP');
INSERT IGNORE INTO `countries` (`id`, `name`, `iso_code`) VALUES (167,'Norway','NO');
INSERT IGNORE INTO `countries` (`id`, `name`, `iso_code`) VALUES (168,'Oman','OM');
INSERT IGNORE INTO `countries` (`id`, `name`, `iso_code`) VALUES (169,'Pakistan','PK');
INSERT IGNORE INTO `countries` (`id`, `name`, `iso_code`) VALUES (170,'Palau','PW');
INSERT IGNORE INTO `countries` (`id`, `name`, `iso_code`) VALUES (171,'Palestine, State of','PS');
INSERT IGNORE INTO `countries` (`id`, `name`, `iso_code`) VALUES (172,'Panama','PA');
INSERT IGNORE INTO `countries` (`id`, `name`, `iso_code`) VALUES (173,'Papua New Guinea','PG');
INSERT IGNORE INTO `countries` (`id`, `name`, `iso_code`) VALUES (174,'Paraguay','PY');
INSERT IGNORE INTO `countries` (`id`, `name`, `iso_code`) VALUES (175,'Peru','PE');
INSERT IGNORE INTO `countries` (`id`, `name`, `iso_code`) VALUES (176,'Philippines','PH');
INSERT IGNORE INTO `countries` (`id`, `name`, `iso_code`) VALUES (177,'Pitcairn','PN');
INSERT IGNORE INTO `countries` (`id`, `name`, `iso_code`) VALUES (178,'Poland','PL');
INSERT IGNORE INTO `countries` (`id`, `name`, `iso_code`) VALUES (179,'Portugal','PT');
INSERT IGNORE INTO `countries` (`id`, `name`, `iso_code`) VALUES (180,'Puerto Rico','PR');
INSERT IGNORE INTO `countries` (`id`, `name`, `iso_code`) VALUES (181,'Qatar','QA');
INSERT IGNORE INTO `countries` (`id`, `name`, `iso_code`) VALUES (182,'Réunion','RE');
INSERT IGNORE INTO `countries` (`id`, `name`, `iso_code`) VALUES (183,'Romania','RO');
INSERT IGNORE INTO `countries` (`id`, `name`, `iso_code`) VALUES (184,'Russian Federation','RU');
INSERT IGNORE INTO `countries` (`id`, `name`, `iso_code`) VALUES (185,'Rwanda','RW');
INSERT IGNORE INTO `countries` (`id`, `name`, `iso_code`) VALUES (186,'Saint Barthélemy','BL');
INSERT IGNORE INTO `countries` (`id`, `name`, `iso_code`) VALUES (187,'Saint Helena, Ascension and Tristan da Cunha','SH');
INSERT IGNORE INTO `countries` (`id`, `name`, `iso_code`) VALUES (188,'Saint Kitts and Nevis','KN');
INSERT IGNORE INTO `countries` (`id`, `name`, `iso_code`) VALUES (189,'Saint Lucie','LC');
INSERT IGNORE INTO `countries` (`id`, `name`, `iso_code`) VALUES (190,'Saint Martin (French part)','MF');
INSERT IGNORE INTO `countries` (`id`, `name`, `iso_code`) VALUES (191,'Saint Pierre and Miquelon','PM');
INSERT IGNORE INTO `countries` (`id`, `name`, `iso_code`) VALUES (192,'Saint Vincent and the Grenadines','VC');
INSERT IGNORE INTO `countries` (`id`, `name`, `iso_code`) VALUES (193,'Samoa','WS');
INSERT IGNORE INTO `countries` (`id`, `name`, `iso_code`) VALUES (194,'San Marino','SM');
INSERT IGNORE INTO `countries` (`id`, `name`, `iso_code`) VALUES (195,'Sao Tome and Principe','ST');
INSERT IGNORE INTO `countries` (`id`, `name`, `iso_code`) VALUES (196,'Saudi Arabia','SA');
INSERT IGNORE INTO `countries` (`id`, `name`, `iso_code`) VALUES (197,'Senegal','SN');
INSERT IGNORE INTO `countries` (`id`, `name`, `iso_code`) VALUES (198,'Serbia','RS');
INSERT IGNORE INTO `countries` (`id`, `name`, `iso_code`) VALUES (199,'Seychelles','SC');
INSERT IGNORE INTO `countries` (`id`, `name`, `iso_code`) VALUES (200,'Sierra Leone','SL');
INSERT IGNORE INTO `countries` (`id`, `name`, `iso_code`) VALUES (201,'Singapore','SG');
INSERT IGNORE INTO `countries` (`id`, `name`, `iso_code`) VALUES (202,'Sint Maarten (Dutch part)','SX');
INSERT IGNORE INTO `countries` (`id`, `name`, `iso_code`) VALUES (203,'Slovakia','SK');
INSERT IGNORE INTO `countries` (`id`, `name`, `iso_code`) VALUES (204,'Slovenia','SI');
INSERT IGNORE INTO `countries` (`id`, `name`, `iso_code`) VALUES (205,'Solomon Islands','SB');
INSERT IGNORE INTO `countries` (`id`, `name`, `iso_code`) VALUES (206,'Somalia','SO');
INSERT IGNORE INTO `countries` (`id`, `name`, `iso_code`) VALUES (207,'South Africa','ZA');
INSERT IGNORE INTO `countries` (`id`, `name`, `iso_code`) VALUES (208,'South Georgia and the South Sandwich Islands','GS');
INSERT IGNORE INTO `countries` (`id`, `name`, `iso_code`) VALUES (209,'South Sudan','SS');
INSERT IGNORE INTO `countries` (`id`, `name`, `iso_code`) VALUES (210,'Spain','ES');
INSERT IGNORE INTO `countries` (`id`, `name`, `iso_code`) VALUES (211,'Sri Lanka','LK');
INSERT IGNORE INTO `countries` (`id`, `name`, `iso_code`) VALUES (212,'Sudan','SD');
INSERT IGNORE INTO `countries` (`id`, `name`, `iso_code`) VALUES (213,'Suriname','SR');
INSERT IGNORE INTO `countries` (`id`, `name`, `iso_code`) VALUES (214,'Svalbard and Jan Mayen','SJ');
INSERT IGNORE INTO `countries` (`id`, `name`, `iso_code`) VALUES (215,'Sweden','SE');
INSERT IGNORE INTO `countries` (`id`, `name`, `iso_code`) VALUES (216,'Switzerland','CH');
INSERT IGNORE INTO `countries` (`id`, `name`, `iso_code`) VALUES (217,'Syrian Arab Republic','SY');
INSERT IGNORE INTO `countries` (`id`, `name`, `iso_code`) VALUES (218,'Taiwan','TW');
INSERT IGNORE INTO `countries` (`id`, `name`, `iso_code`) VALUES (219,'Tajikistan','TJ');
INSERT IGNORE INTO `countries` (`id`, `name`, `iso_code`) VALUES (220,'Tanzania, United Republic of','TZ');
INSERT IGNORE INTO `countries` (`id`, `name`, `iso_code`) VALUES (221,'Thailand','TH');
INSERT IGNORE INTO `countries` (`id`, `name`, `iso_code`) VALUES (222,'Timor-Leste','TL');
INSERT IGNORE INTO `countries` (`id`, `name`, `iso_code`) VALUES (223,'Togo','TG');
INSERT IGNORE INTO `countries` (`id`, `name`, `iso_code`) VALUES (224,'Tokelau','TK');
INSERT IGNORE INTO `countries` (`id`, `name`, `iso_code`) VALUES (225,'Tonga','TO');
INSERT IGNORE INTO `countries` (`id`, `name`, `iso_code`) VALUES (226,'Trinidad and Tobago','TT');
INSERT IGNORE INTO `countries` (`id`, `name`, `iso_code`) VALUES (227,'Tunisia','TN');
INSERT IGNORE INTO `countries` (`id`, `name`, `iso_code`) VALUES (228,'Turkey','TR');
INSERT IGNORE INTO `countries` (`id`, `name`, `iso_code`) VALUES (229,'Turkmenistan','TM');
INSERT IGNORE INTO `countries` (`id`, `name`, `iso_code`) VALUES (230,'Turks and Caicos Islands','TC');
INSERT IGNORE INTO `countries` (`id`, `name`, `iso_code`) VALUES (231,'Tuvalu','TV');
INSERT IGNORE INTO `countries` (`id`, `name`, `iso_code`) VALUES (232,'Uganda','UG');
INSERT IGNORE INTO `countries` (`id`, `name`, `iso_code`) VALUES (233,'Ukraine','UA');
INSERT IGNORE INTO `countries` (`id`, `name`, `iso_code`) VALUES (234,'United Arab Emirates','AE');
INSERT IGNORE INTO `countries` (`id`, `name`, `iso_code`) VALUES (235,'United Kingdom','GB');
INSERT IGNORE INTO `countries` (`id`, `name`, `iso_code`) VALUES (236,'United States','US');
INSERT IGNORE INTO `countries` (`id`, `name`, `iso_code`) VALUES (237,'United States Minor Outlying Islands','UM');
INSERT IGNORE INTO `countries` (`id`, `name`, `iso_code`) VALUES (238,'Uruguay','UY');
INSERT IGNORE INTO `countries` (`id`, `name`, `iso_code`) VALUES (239,'Uzbekistan','UZ');
INSERT IGNORE INTO `countries` (`id`, `name`, `iso_code`) VALUES (240,'Vanuatu','VU');
INSERT IGNORE INTO `countries` (`id`, `name`, `iso_code`) VALUES (241,'Venezuela','VE');
INSERT IGNORE INTO `countries` (`id`, `name`, `iso_code`) VALUES (242,'Viet Nam','VN');
INSERT IGNORE INTO `countries` (`id`, `name`, `iso_code`) VALUES (243,'Virgin Islands, British','VG');
INSERT IGNORE INTO `countries` (`id`, `name`, `iso_code`) VALUES (244,'Virgin Islands, U.S.','VI');
INSERT IGNORE INTO `countries` (`id`, `name`, `iso_code`) VALUES (245,'Wallis and Futuna','WF');
INSERT IGNORE INTO `countries` (`id`, `name`, `iso_code`) VALUES (246,'Western Sahara','EH');
INSERT IGNORE INTO `countries` (`id`, `name`, `iso_code`) VALUES (247,'Yemen','YE');
INSERT IGNORE INTO `countries` (`id`, `name`, `iso_code`) VALUES (248,'Zambia','ZM');
INSERT IGNORE INTO `countries` (`id`, `name`, `iso_code`) VALUES (249,'Zimbabwe','ZW');
